# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('administrators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='exercise.Course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PECollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises', models.ManyToManyField(to='exercise.Exercise')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('alternative_1', models.CharField(max_length=50)),
                ('alternative_2', models.CharField(max_length=50)),
                ('alternative_3', models.CharField(max_length=50)),
                ('alternative_4', models.CharField(max_length=50)),
                ('correct_alternative', models.IntegerField(choices=[(1, 'Alternative 1'), (2, 'Alternative 2'), (3, 'Alternative 3'), (4, 'Alternative 4')], default=1)),
                ('is_worth', models.IntegerField()),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingMaterial',
            fields=[
                ('title', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultVal', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Question')),
            ],
        ),
        migrations.CreateModel(
            name='ResultCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.ManyToManyField(to='exercise.Result')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeTag',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('material', models.ManyToManyField(to='exercise.ReadingMaterial')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='themeTags',
            field=models.ManyToManyField(to='exercise.ThemeTag'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='contains',
            field=models.ManyToManyField(to='exercise.Question'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.ManyToManyField(to='exercise.ReadingMaterial'),
        ),
    ]
