# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_name',
            field=models.CharField(default='Empty', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='exercise',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
            preserve_default=False,
        ),
    ]
