# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
